baseurl = "/"
DefaultContentLanguage = "en"
title = "PA2DK"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Dutch Amateur Radio Station"
  mainSections = []
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
  selfHosted = true

[[Params.bigimg]]
  src = "img/gpsdo.jpg"
  desc = "GPSDO"

[Author]
  name = "Dennis PA2DK"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    identifier = "log"
    name = "Log"
    url = "page/log/"
    weight = 2

[[menu.main]]
    parent = "log"
    name = "PA2DK"
    url = "page/log_pa2dk/"
    weight = 1

[[menu.main]]
    parent = "log"
    name = "PA2DK/P"
    url = "page/log_pa2dk_p"
    weight = 2

[[menu.main]]
    identifier = "Wiki"
    name = "Wiki"
    url = "https://wiki.pa2dk.nl"
    hrefTargetBlank = true
    weight = 3

[markup.goldmark.renderer]
unsafe = true